# Generated by Django 3.0.8 on 2020-10-11 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='contact',
            new_name='user_inform',
        ),
    ]
